"""Constants for the ConnectLife integration."""

DOMAIN = "connectlife"

ATTR_DEVICE = "device"
ATTR_DESC = "desc"
ATTR_KEY = "key"

CONF_DEVICES = "devices"
CONF_DEVELOPMENT_MODE = "development_mode"
CONF_DISABLE_BEEP = "disable_beep"
CONF_TEST_SERVER_URL = "test_server_url"

ACTION = "action"
CURRENT_OPERATION = "current_operation"
HVAC_ACTION = "hvac_action"
HVAC_MODE = "hvac_mode"
FAN_MODE = "fan_mode"
IS_ON = "is_on"
IS_AWAY_MODE_ON = "is_away_mode_on"
MODE = "mode"
PRESET = "preset"
PRESETS = "presets"
STATE = "state"
SWING_MODE = "swing_mode"
TARGET_HUMIDITY = "target_humidity"
TARGET_TEMPERATURE = "target_temperature"
TEMPERATURE_UNIT = "temperature_unit"
