"""Constants for the ConnectLife integration."""

DOMAIN = "connectlife"

ATTR_DEVICE = "device"
ATTR_DESC = "desc"
ATTR_KEY = "key"

ACTION = "action"
CURRENT_OPERATION = "current_operation"
HVAC_ACTION = "hvac_action"
HVAC_MODE = "hvac_mode"
FAN_MODE = "fan_mode"
IS_ON = "is_on"
IS_AWAY_MODE_ON = "is_away_mode_on"
MODE = "mode"
STATE = "state"
SWING_MODE = "swing_mode"
TARGET_HUMIDITY = "target_humidity"
TARGET_TEMPERATURE = "target_temperature"
TEMPERATURE_UNIT = "temperature_unit"
